### ISSUE TITLE
Problema ao rodar o Webpack /Modulo 1+ webpack 

### ISSUE THREAD

**Issue by Srdeveloperpika** [da2k/curso-reactjs-ninja#112]
Instalo tudo certo e faço as configurções básicas no webpack. Mas quando dou o comando 'Webpack' no terminal, aparece: "The CLI moved into a separate package: webpack-cli
Would you like to install webpack-cli? (That will run npm install -D webpack-cli) (yes/NO)".
Não importa oq eu faça sempre que eu vou gerar o bundle.js aparece isso.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Srdeveloperpika! O problema é a versão do webpack que você está usando =)

Nesse módulo, estamos usando a versão `1` do webpack, então, para que tudo funcione como mostrado nas aulas, é necessário instalar as versões exatas das dependências usadas =)

Para saber quais foram as versões usadas nesse módulo, você pode consultar [esse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md), onde eu mantenho tudo atualizado para que você consiga acompanhar todo o curso sem maiores problemas :)

**Comment by Srdeveloperpika** [comment]
Instalei o webpack na versão certa como dependencia global, agora quando dou o comando webpack aparece isso : " filename: 'bundle.js'
                ^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at module.exports (C:\Users\Tales\AppData\Roaming\npm\node_modules\webpack\bin\convert-argv.js:80:13)"
oq faço?

**Comment by Srdeveloperpika** [comment]
Resolvi, o problema era: não botei uma virgula antes do filename e também o __dirname estava errado.

**Comment by Srdeveloperpika** [comment]
Obrigado pela ajuda. :)

**Comment by ffabiorj** [comment]
@fdaciuk no meu esta dando esse erro aqui

/Users/fabio/Desktop/projetos/react/node_modules/webpack-cli/bin/webpack.js:242
				throw err;
				^

TypeError: validateSchema is not a function
    at processConfiguredOptions (/Users/fabio/Desktop/projetos/react/node_modules/webpack-cli/bin/convert-argv.js:156:48)
    at module.exports (/Users/fabio/Desktop/projetos/react/node_modules/webpack-cli/bin/convert-argv.js:150:10)
    at yargs.parse (/Users/fabio/Desktop/projetos/react/node_modules/webpack-cli/bin/webpack.js:239:39)
    at Object.parse (/Users/fabio/Desktop/projetos/react/node_modules/webpack-cli/node_modules/yargs/yargs.js:552:18)
    at /Users/fabio/Desktop/projetos/react/node_modules/webpack-cli/bin/webpack.js:217:8
    at Object.<anonymous> (/Users/fabio/Desktop/projetos/react/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at module.exports.filename (/usr/local/lib/node_modules/webpack-cli/node_modules/import-local/index.js:16:66)
    at /usr/local/lib/node_modules/webpack-cli/bin/webpack.js:13:6
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack-cli/bin/webpack.js:514:3)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/webpack/bin/webpack.js:12:2)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)

**Comment by fdaciuk** [comment]
Legal que deu certo @Srdeveloperpika! =)

@ffabiorj o seu problema é o problema inicial do @Srdeveloperpika: a versão do webpack =)
Dá uma olhada [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) que mostra as versões corretas que você precisa usar pra conseguir acompanhar o curso corretamente =)

**Comment by ffabiorj** [comment]
resolvido. Pode fechar issue.

**Comment by ffabiorj** [comment]
@fdaciuk

**Comment by fdaciuk** [comment]
Opa, show =)
