### ISSUE TITLE
[M02A02]

### ISSUE THREAD

**Issue by kelsonthony** [da2k/curso-reactjs-ninja#130]
Olá Fernando, estou com 2 problemas,
Usando o comando npm test, o teste é bem lento, executa sem erros, mas demora muito

Outro problema é com o npm run eject, não consigo executar como você fez

veja meu log

```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\kanthony\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'eject' ]
2 info using npm@5.0.3
3 info using node@v8.9.4
4 verbose run-script [ 'preeject', 'eject', 'posteject' ]
5 info lifecycle cra@0.1.0~preeject: cra@0.1.0
6 silly lifecycle cra@0.1.0~preeject: no script for preeject, continuing
7 info lifecycle cra@0.1.0~eject: cra@0.1.0
8 verbose lifecycle cra@0.1.0~eject: unsafe-perm in lifecycle true
9 verbose lifecycle cra@0.1.0~eject: PATH: C:\Users\kanthony\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\ReactJS\modulo-2\cra\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;c:\Program Files\Intel\WiFi\bin\;c:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\MySQL\MySQL Utilities 1.6\;C:\Program Files (x86)\sqlite3;%JAVA_HOME%\bin;%CATALINA_HOME%\bin;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\IDM Computer Solutions\UltraEdit;C:\Users\kanthony\AppData\Local\Microsoft\WindowsApps;C:\Users\kanthony\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin;C:\Users\kanthony\AppData\Local\GitHubDesktop\bin
10 verbose lifecycle cra@0.1.0~eject: CWD: C:\ReactJS\modulo-2\cra
11 silly lifecycle cra@0.1.0~eject: Args: [ '/d /s /c', 'react-scripts eject' ]
12 silly lifecycle cra@0.1.0~eject: Returned: code: 1  signal: null
13 info lifecycle cra@0.1.0~eject: Failed to exec eject script
14 verbose stack Error: cra@0.1.0 eject: `react-scripts eject`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Users\kanthony\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Users\kanthony\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid cra@0.1.0
16 verbose cwd C:\ReactJS\modulo-2\cra
17 verbose Windows_NT 10.0.14393
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\kanthony\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "eject"
19 verbose node v8.9.4
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 1
23 error cra@0.1.0 eject: `react-scripts eject`
23 error Exit status 1
24 error Failed at the cra@0.1.0 eject script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Obrigado

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Para chegar nesse erro, você criou o projeto com o `create-react-app`, e então já tentou rodar o `npm run eject`? Ou fez alguma coisa a mais?

**Comment by kelsonthony** [comment]
Olá @fdaciuk bom-dia.
Não fiz nada de diferente, fiz exatamente igual vc mostrou na aula. Entretanto, lendo em fóruns, tinha uma turma recomendando commitar o código para executar o npm run eject. eu fiz isso e deu certo. gostaria de ver meu código?

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Estranho só ter comitado e já ter funcionado xD
Pode ser algum problema específico do windows então, não sei te dizer =)

Mas deu certo? Você conseguiu resolver o problema? Se sim, pode seguir em frente =)
Senão, posta o link do repo aqui que eu vou tentando te ajudar a resolver =)

**Comment by kelsonthony** [comment]
Olá Professor @fdaciuk, boa-noite, eu refiz o processo em um ambiente unix e tudo deu certo de primeira, não foi necessário nenhum commit. Como não tenho preferência de ambientes, posso seguir usando linux sem problemas. 
Obrigado e vamos que vamos.

**Comment by fdaciuk** [comment]
Legal @kelsonthony! Qualquer coisa, só avisar =)
