### ISSUE TITLE
MRW#A02 - Configuração basica webpack

### ISSUE THREAD

**Issue by diegopgcabral** [da2k/curso-reactjs-ninja#136]
Estou com a seguinte duvida:

Meu arquivo package.json está assim:

{
  "devDependencies": {
    "webpack": "^1.13.1"
  }
}

arquivo webpack.config.js

'use strict'

const path = require('path')

module.exports = {
	entry: path.join(__dirname,'src','index')
	output: {
		path: path.join(__dirname,'dist'),
		filename: 'bundle.js'
	}
}

instalei esse webpack no diretorio:
**npm install --save-dev webpack@1**

instalei o npm i - g webpack (global) e após a instalação quando digito webpack estou recebendo a seguinte msg:

```
C:\Users\Diego\Desktop\Research\react-webpack>webpack
C:\Users\Diego\Desktop\Research\react-webpack\webpack.config.js:7
        output: {
        ^^^^^^
SyntaxError: Unexpected identifier
    at NativeCompileCache._moduleCompile (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:226:18)
    at Module._compile (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:172:36)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at WEBPACK_OPTIONS (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (native)
    at module.exports (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at yargs.parse.err (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\bin\cli.js:241:39)
    at Object.parse (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\node_modules\yargs\yargs.js:552:18)
    at C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\bin\cli.js:219:8
    at Object.<anonymous> (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack-cli\bin\cli.js:530:3)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\Diego\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:157:2)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```
poderia me ajudar???

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @diegopgcabral! Faltou uma vírgula ali, no final da linha do `entry`, antes do `output`, por isso esse erro =)

Só lembrando que a versão global também precisar ser instalada com `webpack@1`, senão vai dar outro erro, ok? =)

**Comment by diegopgcabral** [comment]
Muito Obrigado! 
Resolvido.

**Comment by fdaciuk** [comment]
Qualquer coisa, só avisar =)
