### ISSUE TITLE
[M2#A08] Watch lento

### ISSUE THREAD

**Issue by kelsonthony** [da2k/curso-reactjs-ninja#141]
Olá @fdaciuk gostaria de saber pq o watch é tão lento no windows. um watch está levando quase 10min para executar. teria alguma ideia?
Obrigado. 

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Não deveria ser tão lento assim não xD
Consegue compartilhar seu projeto pra eu testar no Linux aqui? Sobe ele em um repo aqui no GitHub que a gente já vê qual é o problema =)

**Comment by kelsonthony** [comment]
Olá @fdaciuk tudo bem?
Aqui está o meu código: https://github.com/kelsonthony/jest-in-practice 
Após clonar novamente o item do meu repositório não vejo o problema de lentidão ocorrer novamente no windows.
Já no linux, quando tento quebrar um teste, o teste passa normalmente.
Além disso, no windows, quando faço o segundo teste passar pelo 3x, ele passa, mas no terminal me aparece o seguinte erro

 PASS  .\sum.test.js
  √ sum should be a function
  √ sum(1, 2) should  return 3

Running coverage on untested files...Failed to collect coverage from C:\ReactJS\jest-in-practice\coverage\coverage-final.json
ERROR: Unexpected token, expected ; (1:40)
STACK: SyntaxError: Unexpected token, expected ; (1:40)
    at Parser.pp$5.raise (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp.semicolon (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:2236:8)
    at Parser.parseExpressionStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:5934:20)
    at Parser.pp$1.parseStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:1911:17)
    at Parser.parseStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:5910:22)
    at Parser.pp$1.parseBlockBody (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseBlock (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:2247:8)
    at Parser.pp$1.parseStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:1868:19)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 passed, 1 total
Tests:       2 passed, 2 total
Snapshots:   0 total
Time:        2.004s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.

Após dar exit e voltar a rodar o watch, o teste passa de forma normal.

Esse comportamento é esperado?

Obrigado.

**Comment by fdaciuk** [comment]
Legal @kelsonthony! Esse problema provavelmente é cache! Você pode trocar o script que roda o teste, de `jest --coverage` para `jest --coverage --clearCache` =)

**Comment by kelsonthony** [comment]
Olá @fdaciuk ok, eu fiz isso e melhorou um pouco, continua lento. acho que vou pro linux mesmo.
Gostaria de saber desse erro que está aparecendo do coverage, sempre aparace, mesmo se eu excluir a pasta, ele volta aparecer
Running coverage on untested files...Failed to collect coverage from C:\ReactJS\jest-in-practice\coverage\coverage-final.json
ERROR: Unexpected token, expected ; (1:40)
STACK: SyntaxError: Unexpected token, expected ; (1:40)
at Parser.pp$5.raise (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:4454:13)
at Parser.pp.unexpected (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:1761:8)
at Parser.pp.semicolon (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:1742:38)
at Parser.pp$1.parseExpressionStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:2236:8)
at Parser.parseExpressionStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:5934:20)
at Parser.pp$1.parseStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:1911:17)
at Parser.parseStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:5910:22)
at Parser.pp$1.parseBlockBody (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:2268:21)
at Parser.pp$1.parseBlock (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:2247:8)
at Parser.pp$1.parseStatement (C:\ReactJS\jest-in-practice\node_modules\babylon\lib\index.js:1868:19)

Obrigado.

**Comment by fdaciuk** [comment]
Esse erro só acontece no windows? Consegue me passar os passos pra simular? Tentei rodar no Linux e rodou certinho, sem esse erro =)

Se puder também tirar um print do seu terminal, ao invés de colocar aqui o resultado, só pra eu ver se tem algum caractere especial que ele está dando erro =)

**Comment by kelsonthony** [comment]
Oi Professor @fdaciuk  testei no linux e está dando o mesmo erro, ele tá reclamando do coverage

 FAIL  src/map.test.js
  ✓ map should be a function (3ms)
  ✓ map([1, 2], (item) => item) should return [1, 2] (1ms)
  ✕ map([3, 4] (item) =>) should return [1, 2] (36ms)

  ● map([3, 4] (item) =>) should return [1, 2]

    AssertionError: expected [ 1, 2 ] to deeply equal [ 3, 4 ]

      13 | 
      14 | it('map([3, 4] (item) =>) should return [1, 2]', () => {
    > 15 |   expect(map([3, 4], (item) => item)).to.be.deep.equal([3, 4])
         |                                                  ^
      16 | })

      at Proxy.assertEqual (node_modules/chai/lib/chai/core/assertions.js:1020:19)
      at Proxy.methodWrapper (node_modules/chai/lib/chai/utils/addMethod.js:57:25)
      at Object.<anonymous> (src/map.test.js:15:50)

Running coverage on untested files...Failed to collect coverage from /home/reactjs/teste-map/package.json
ERROR: Unexpected token, expected ; (2:11)
STACK: SyntaxError: Unexpected token, expected ; (2:11)
    at Parser.pp$5.raise (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.semicolon (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:2236:8)
    at Parser.parseExpressionStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:5934:20)
    at Parser.pp$1.parseStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:1911:17)
    at Parser.parseStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$1.parseStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:1868:19)
Failed to collect coverage from /home/reactjs/teste-map/coverage/coverage-final.json
ERROR: Unexpected token, expected ; (1:78)
STACK: SyntaxError: Unexpected token, expected ; (1:78)
    at Parser.pp$5.raise (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp.semicolon (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:2236:8)
    at Parser.parseExpressionStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:5934:20)
    at Parser.pp$1.parseStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:1911:17)
    at Parser.parseStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:5910:22)
    at Parser.pp$1.parseBlockBody (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:2268:21)
    at Parser.pp$1.parseBlock (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:2247:8)
    at Parser.pp$1.parseStatement (/home/reactjs/teste-map/node_modules/babylon/lib/index.js:1868:19)
----------------------|----------|----------|----------|----------|-------------------|
File                  |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------------------|----------|----------|----------|----------|-------------------|
All files             |     0.33 |        0 |     1.89 |     1.87 |                   |
 coverage/lcov-report |        0 |        0 |        0 |        0 |                   |
  block-navigation.js |        0 |        0 |        0 |        0 |... 53,54,58,59,63 |
  prettify.js         |        0 |        0 |        0 |        0 |                 1 |
  sorter.js           |        0 |        0 |        0 |        0 |... 52,153,154,158 |
 src                  |      100 |      100 |      100 |      100 |                   |
  map.js              |      100 |      100 |      100 |      100 |                   |
----------------------|----------|----------|----------|----------|-------------------|
Test Suites: 1 failed, 1 total
Tests:       1 failed, 2 passed, 3 total
Snapshots:   0 total
Time:        4.111s
Ran all test suites related to changed files.

Watch Usage
![captura de tela de 2018-06-18 23-13-13](https://user-images.githubusercontent.com/7318326/41572239-4328927a-734d-11e8-80f0-71073c088757.png)

Repositório do exemplo: https://github.com/kelsonthony/teste-map

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Esse erro pode ser porque você versionou o diretório node_modules! Remova esse diretório e instale novamente as dependências, com `npm install` ou `yarn` (se estiver usando o `yarn`) =)

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
