### ISSUE TITLE
M2 A#11

### ISSUE THREAD

**Issue by kelsonthony** [da2k/curso-reactjs-ninja#147]
Olá @fdaciuk boa-noite.

O nodejs está matando minha minha, veja esse erro

 RUNS  src/map.test.js

<--- Last few GCs --->

[11408:0000024951A8E420]   142390 ms: Mark-sweep 1402.6 (1535.8) -> 1402.5 (1508.8) MB, 1769.4 / 0.0 ms  (+ 0.0 ms in 0 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1773 ms) last resort GC in old space requested
[11408:0000024951A8E420]   144312 ms: Mark-sweep 1402.5 (1508.8) -> 1402.5 (1508.8) MB, 1921.9 / 0.0 ms  last resort GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0000028B13E25EE1 <JSObject>
    2: exec(this=0000026850362549 <JSRegExp <String[84]: ^(?:(?:\.[\\\/](?=.))?\..\teste-assertion\node_modules\es-abstract\test\es2015\.js)$>>,00000268503636C1 <String[43]: node_modules/regenerator-runtime/runtime.js>)
    3: test(this=0000026850362549 <JSRegExp <String[84]: ^(?:(?:\.[\\\/](?=.))?\..\teste-assertion\node_modules\es-abstract\test\es2015\.js)$>>,00000268503636C1 <String[43]: no...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node_module_register
 2: v8::internal::FatalProcessOutOfMemory
 3: v8::internal::FatalProcessOutOfMemory
 4: v8::internal::Factory::NewCodeRaw
 5: v8::internal::Factory::NewCode
 6: v8::internal::interpreter::operator<<
 7: v8::internal::RegExpImpl::Exec
 8: v8::internal::RegExpImpl::Exec
 9: v8::internal::RegExpImpl::Exec
10: v8::internal::RegExpImpl::Exec
11: v8::internal::RegExpImpl::Exec
12: v8::internal::RegExpImpl::Exec
13: v8::internal::ParserBase<v8::internal::Parser>::MarkLoopVariableAsAssigned
14: 0000008147E047A1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ test:watch: `npm test -- --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ test:watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\kanthony\AppData\Roaming\npm-cache\_logs\2018-06-28T04_28_19_793Z-debug.log

C:\ReactJS\modulo-2\new-test>

![node-memory](https://user-images.githubusercontent.com/7318326/42013334-1c0c0bea-7a73-11e8-91d4-98103e5d9fb1.png)

![erro-teste-watch-1](https://user-images.githubusercontent.com/7318326/42013342-279fe4cc-7a73-11e8-891f-40bf8b321fd1.png)
![erro-teste-watch-2](https://user-images.githubusercontent.com/7318326/42013343-27c31064-7a73-11e8-8d4d-14a4ba992e15.png)

Se puder me ajudar.

obrigado.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Consegue me mostrar como está o conteúdo desse seu arquivo `map.test.js` e do arquivo que está sendo testado? Se conseguir subir o projeto em um repositório aqui no GitHub, melhor =)

**Comment by kelsonthony** [comment]
Olá Prof. @fdaciuk boa-noite.
este é o projeto que está com problema, se puder me dar uma luz, tentei de novo mesmo.
https://github.com/kelsonthony/new-test-map

Muito obrigado.

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Faltou no seu projeto criar o `.babelrc` para o Jest conseguir saber quais presets do babel você está usando =)

Crie na raiz da sua aplicação um arquivo chamado `.babelrc`, e coloque o conteúdo dele assim:

```json
{
  "presets": ["es2015", "stage-0"]
}
```

Isso já deve funcionar =)

**Comment by kelsonthony** [comment]
Olá Prof. @fdaciuk bom-dia.
De fato estava faltando este item.
Refiz o projeto do zero e agora funcionou, sem lentidão, e os testes passaram. agora estou apenas com o problema do coverage.

Veja abaixo

 PASS  src/map.test.js (6.85s)
  √ map should be a function
  √ map([1, 2], (item) => item) should return [1, 2]
  √ map([3, 4] (item) =>) should return [1, 2]
  √ map([1, 2], (item) => item + 1) should return [2, 3]
  √ map([4, 6], (item) => item + 1) should return [5, 7]
  √ map([1, 2], (item, index) => index) should return [0, 1]
  √ map([1, 2], (item, index, array) => array) should return [[1, 2], [1, 2]]
  √ map() should return []
  √ map([1, 2]) should return [1, 2]

Running coverage on untested files...Failed to collect coverage from C:\ReactJS\modulo-2\test-map-new\package.json
ERROR: Unexpected token, expected ; (2:11)
STACK: SyntaxError: Unexpected token, expected ; (2:11)
    at Parser.pp$5.raise (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp.semicolon (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:2236:8)
    at Parser.parseExpressionStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:5934:20)
    at Parser.pp$1.parseStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:1911:17)
    at Parser.parseStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:5910:22)
    at Parser.pp$1.parseBlockBody (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseBlock (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:2247:8)
    at Parser.pp$1.parseStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:1868:19)
Failed to collect coverage from C:\ReactJS\modulo-2\test-map-new\coverage\coverage-final.json
ERROR: Unexpected token, expected ; (1:51)
STACK: SyntaxError: Unexpected token, expected ; (1:51)
    at Parser.pp$5.raise (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp.semicolon (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:1742:38)
    at Parser.pp$1.parseExpressionStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:2236:8)
    at Parser.parseExpressionStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:5934:20)
    at Parser.pp$1.parseStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:1911:17)
    at Parser.parseStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:5910:22)
    at Parser.pp$1.parseBlockBody (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:2268:21)
    at Parser.pp$1.parseBlock (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:2247:8)
    at Parser.pp$1.parseStatement (C:\ReactJS\modulo-2\test-map-new\node_modules\babylon\lib\index.js:1868:19)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |      100 |      100 |                   |
 map.js   |      100 |      100 |      100 |      100 |                   |
----------|----------|----------|----------|----------|-------------------|
Test Suites: 1 passed, 1 total
Tests:       9 passed, 9 total
Snapshots:   0 total
Time:        8.355s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.

prints do terminal

![erro-project-test-map-new-1](https://user-images.githubusercontent.com/7318326/42125921-038178aa-7c56-11e8-8137-41fa3386aaaf.png)

![erro-project-test-map-new-2](https://user-images.githubusercontent.com/7318326/42125923-09f10458-7c56-11e8-88a1-d431dc4bb2bb.png)


O projeto: https://github.com/kelsonthony/test-map-new 

Muito obrigado pela atenção.

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Tente remover o diretório `coverage` e o `node_modules` e instalar as dependências novamente (`npm install` ou `yarn`, se estiver usando Yarn).

E como dica, nunca versione esses dois diretórios, pois eles são gerados automaticamente. Esse problema provavelmente é porque você está reutilizando esses diretórios que deveriam ser gerados a cada nova instalação =)

Detalhe: não sei se você está usando essa dependência `node-modules`, pode ser que você tenha instalado sem querer. Se foi esse o caso, pode remover com `npm uninstall node-modules` (ou `yarn remove node-modules`, se estiver usando Yarn).

Se você instalou porque quis, só ignore =)

**Comment by fdaciuk** [comment]
Oi @kelsonthony! Deu certo? Vou fechar a issue, mas se você ainda tiver problemas, eu reabro, ok? =)
