### ISSUE TITLE
[MRW02] - Erro ao digitar webpack

### ISSUE THREAD

**Issue by alexmpereira** [da2k/curso-reactjs-ninja#158]
Ao digitar o comando webpack, ele retorna a seguinte mensagem:

```
One CLI for webpack must be installed. These are recommended choices, delivered as separate packages:
 - webpack-cli (https://github.com/webpack/webpack-cli)
   The original webpack full-featured CLI.
 - webpack-command (https://github.com/webpack-contrib/webpack-command)
   A lightweight, opinionated webpack CLI.
We will use "npm" to install the CLI via "npm install -D".
Which one do you like to install (webpack-cli/webpack-command):
```

Tentei as duas opções e sempre no final, mostra essa mensagem:

```
+ webpack-cli@3.0.8
updated 1 package in 13.327s
{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (module.js:557:15)
    at Function.Module._load (module.js:484:25)
    at Module.require (module.js:606:17)
    at require (internal/module.js:11:18)
    at runCommand.then (C:\Users\55449\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:152:5)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7) code: 'MODULE_NOT_FOUND' }
```

Alguma sugestão para eu resolver?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @alexmpereira! Conseguiu resolver? =)

**Comment by mat55** [comment]
@fdaciuk Também estou enfrentando o mesmo problema

**Comment by fdaciuk** [comment]
@mat55 dá uma olhada [nessa issue](https://github.com/da2k/curso-reactjs-ninja/issues/153), que tem a solução =)

**Comment by fdaciuk** [comment]
Show @mat55! Qualquer dúvida, só avisar =)
