### ISSUE TITLE
M2#A46 - Storybook - storybook com erro.

### ISSUE THREAD

**Issue by gustavom** [da2k/curso-reactjs-ninja#194]
Fernando, realmente não sei o que aconteceu, fiquei um tempo se ver as aulas, quando voltei, o storybook não roda.

`λ npm run storybook

> @ storybook C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app
> start-storybook -p 6006 -c storybook

@kadira/storybook v2.35.3

=> Loading custom .babelrc
module.js:538
    throw err;
    ^

Error: Cannot find module '@kadira/storybook/dist'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app\storybook\webpack.config.js:3:23)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ storybook: `start-storybook -p 6006 -c storybook`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

Meu projeto: https://github.com/gustavom/curso-react-ninja/tree/master/m02/working-with-assets/github-app

@fdaciuk

**Comment by fdaciuk** [comment]
@gustavom rodei o projeto aqui, e consegui reproduzir seu problema =)
Dá uma olhada na mensagem de erro. Se você for passando linha a linha, você vai conseguir ver que o erro aconteceu em um arquivo do seu projeto. Especificamente nessa linha:

```
at Object. (C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app\storybook\webpack.config.js:3:23)
```

Ao abrir o arquivo `storybook/webpack.config.js`, na linha `3`, você pode ver que o erro está ali: o caminho do `webpackConfig` do storybook está incompleto =)

Dá uma olhada na aula que lá tem o caminho correto que você precisa usar pra fazer o require do arquivo, ok? =)

**Comment by gustavom** [comment]
Arrumei o caminho do arquivo. Agora o erro é outro:

`λ npm run storybook

> @ storybook C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app
> start-storybook -p 6006 -c storybook

@kadira/storybook v2.35.3

=> Loading custom .babelrc
C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app\storybook\webpack.config.js:27
module.exports = function (config. env) {
                                 ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at exports.default (C:\Users\gmartusewicz\Documents\gustavo\Curso react ninja Da2k\Exercicios\m02\working-with-assets\github-app\node_modules\@kadira\storybook\dist\server\config.js:51:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ storybook: `start-storybook -p 6006 -c storybook`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ storybook script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:`

**Comment by fdaciuk** [comment]
Opa! Legal =)
Agora dá uma olhada nesse erro que ele tá te dando a dica de onde está o problema =)

Nessa linha:

```
module.exports = function (config. env) {
^
```

Ele exibe o erro:

```
SyntaxError: Unexpected token .
```

**Comment by gustavom** [comment]
Nossa, desencana.

Eu não percebi isso.

Estou usando o cmder no windows. Esses erros so aparecem quando seleciono o texto para copiar e colar, mas no terminal direto, fica sem fonte.

Sem selecionar, o que aparecia:
![capturar](https://user-images.githubusercontent.com/910377/45641319-86d31100-ba8b-11e8-9a97-2632b5c9ac83.PNG)

Selecionando o texto, eu fiz rápido e nem percebi, nas duas vezes:

![capturar2](https://user-images.githubusercontent.com/910377/45641321-876ba780-ba8b-11e8-81de-16d32eb0737d.PNG)

**Comment by gustavom** [comment]
Arrumei com o erros que apareciam, voltou a rodar.

**Comment by fdaciuk** [comment]
Que bizarro! Provavelmente é alguma configuração do cmder. Deve ter alguma configuração pra cor que está deixando fundo e fonte pretos =)

Mas legal que rodou! Qualquer dúvida avisa ae :D
