### ISSUE TITLE
[MRW#08] - Erro na execução npm server.js

### ISSUE THREAD

**Issue by GugaDavi** [da2k/curso-reactjs-ninja#321]
Opa Daciuk, Boa Tarde,

Suave?

Brow fiz como dito na aula, fiz as instalações conforme o link que você disponibilizou, confesso que durante algumas instalações tiveram alguns erros, mas tudo estava funcionando exatamente como você apresentava. Dai fiz o os mesmos passos como na aula do MRW#08, mas quando executo o `npm start` dá a seguinte mensagem:

`@ start /media/Gustavo/Cursos/Projeto Web/React
> node server.js

/media/Gustavo/Cursos/Projeto Web/React/node_modules/schema-utils/src/validateOptions.js:32
    throw new ValidationError(ajv.errors, name);
    ^

ValidationError: webpack Dev Server Invalid Options

options should NOT have additional properties

    at validateOptions (/media/Gustavo/Cursos/Projeto Web/React/node_modules/schema-utils/src/validateOptions.js:32:11)
    at new Server (/media/Gustavo/Cursos/Projeto Web/React/node_modules/webpack-dev-server/lib/Server.js:87:5)
    at Object.<anonymous> (/media/Gustavo/Cursos/Projeto Web/React/server.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/gustavo/.npm/_logs/2019-05-13T22_58_13_741Z-debug.log`

Tive outros erros antes desses, mas consegui resolver pesquisando, mas esse tá osso.

@fdaciuk

**Comment by GugaDavi** [comment]
Consegui ajustar, na verdade foi algumas das versões que estavam diferente dos que você usou. Não sei porque, fiz copiando os códigos do link, bom... Deixa quieto. Agora estou com outros dois problemas.

1) Quando dei o npm start ele deu um erro na syntax, dai tive que retirar o JSX do index.js. Ele parou de compilar com o JSX
2) Dai já entra no segundo problema: Mesmo retirando o JSX ele não está compilando corretamente, o bundle.js que está na pasta "dist" está vazio, muito bem ele conclui a execução do servidor, mas ele simplesmente está puxando o bundle vazio e não renderizando o index.js.

Estava tudo funcionando, mas depois das alterações, miou.

**Comment by GugaDavi** [comment]
Desculpa a quantidade de mensagens, serio mesmo! kkkk

Consegui resolver os problemas.

O lance do JSX foi erro de digitação no server.js;

O segundo foi erro de digitação também webpack.config.js

Mlz pelo trabalho, vlw!

@fdaciuk

**Comment by fdaciuk** [comment]
haha! Tranquilo @GugaDavi! Qualquer dúvida, pode sempre perguntar :)
