### ISSUE TITLE
M1#A13 - erro 

### ISSUE THREAD

**Issue by TMiranda7** [da2k/curso-reactjs-ninja#337]
comparei com o codigo do próprio projeto , não achei diferenças
sobre o erro apresentado , não tenho ideia do que se trata

[HMR] Waiting for update signal from WDS...
warning.js:33 Warning: Square(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
printWarning @ warning.js:33
AppContainer.dev.js:95 Invariant Violation: Square(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
    at invariant (http://localhost:3001/static/bundle.js:1753:16)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3001/static/bundle.js:30868:115)
    at Object.mountComponent (http://localhost:3001/static/bundle.js:23426:36)
    at ReactDOMComponent.mountChildren (http://localhost:3001/static/bundle.js:30078:45)
    at ReactDOMComponent._createInitialChildren (http://localhost:3001/static/bundle.js:27162:33)
    at ReactDOMComponent.mountComponent (http://localhost:3001/static/bundle.js:26981:13)
    at Object.mountComponent (http://localhost:3001/static/bundle.js:23426:36)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3001/static/bundle.js:31044:35)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3001/static/bundle.js:30931:22)
    at Object.mountComponent (http://localhost:3001/static/bundle.js:23426:36)
render @ AppContainer.dev.js:95
warning.js:33 Warning: Square(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
printWarning @ warning.js:33
invariant.js:49 Uncaught Invariant Violation: Square(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
    at invariant (http://localhost:3001/static/bundle.js:1753:16)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3001/static/bundle.js:30868:115)
    at Object.mountComponent (http://localhost:3001/static/bundle.js:23426:36)
    at ReactDOMComponent.mountChildren (http://localhost:3001/static/bundle.js:30078:45)
    at ReactDOMComponent._createInitialChildren (http://localhost:3001/static/bundle.js:27162:33)
    at ReactDOMComponent.mountComponent (http://localhost:3001/static/bundle.js:26981:13)
    at Object.mountComponent (http://localhost:3001/static/bundle.js:23426:36)
    at ReactCompositeComponentWrapper.performInitialMount (http://localhost:3001/static/bundle.js:31044:35)
    at ReactCompositeComponentWrapper.mountComponent (http://localhost:3001/static/bundle.js:30931:22)
    at Object.mountComponent (http://localhost:3001/static/bundle.js:23426:36)
client?e36c:37 [WDS] Hot Module Replacement enabled.
client?e36c:37 [WDS] Warnings while compiling.
client?e36c:68 ./src/square.js
<text>:6:3: Expected an assignment or function call and instead saw an expression.
warnings @ client?e36c:68

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @TMiranda7! O seu problema é algum componente que não está retornando nada =)
Veja a primeira linha com warning:

```
warning.js:33 Warning: Square(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.
```

Provavelmente o seu componente `Square` não está retornando nada :)

**Comment by TMiranda7** [comment]
Deu certo ,mestre

**Comment by fdaciuk** [comment]
Perfeito @TMiranda7! Qualquer dúvida, só avisar :)
