### ISSUE TITLE
m2A73

### ISSUE THREAD

**Issue by RodrigoWP** [da2k/curso-reactjs-ninja#34]
Fala Daciuk!

Estou construindo um script de atualização utilizando o `child-process` semelhante ao que fizemos na aula 73 do modulo 2, e está me retornando um erro ao executar o comando `yarn add`, segue:

```
Error: spawn yarn ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3
```

Sabe o que pode ser?

Obs: Estou usando a versão 7.9.0 do node

Valeu!

**Comment by fdaciuk** [comment]
Fala @RodrigoWP! Você está usando windows, correto?

O @hgtpcastro teve o mesmo problema. Ele acabou chegando [nessa solução](https://github.com/da2k/curso-reactjs-ninja/issues/32#issuecomment-294932181).

Veja se resolve pra você =)

**Comment by RodrigoWP** [comment]
Show @fdaciuk , funcionou perfeitamente!

Muito obrigado!

**Comment by fdaciuk** [comment]
Boa! Qualquer coisa só avisar =)
