### ISSUE TITLE
M2 - Erro para buildar

### ISSUE THREAD

**Issue by rafaelsevla** [da2k/curso-reactjs-ninja#364]
Estou tendo um erro para fazer build da aplicação, algo com relacionado a depreciação, quando uso o comando `yarn build` tenho  o seguinte problema:

```
clean-webpack-plugin: /Users/rafaelcosta/workspace/React-Ninja/markdown-editor/dist has been removed.
 10% building modules 0/1 modules 1 active ...ct-Ninja/markdown-editor/src/index.js(node:17204) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
    at Object.parseQuery (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/loader-utils/index.js:78:3)
    at Object.standardLoader (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/standard-loader/index.js:15:17)
    at LOADER_EXECUTION (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
    at runSyncOrAsync (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
    at iterateNormalLoaders (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
    at Array.<anonymous> (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
    at Storage.finished (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:40:15)
    at /Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:77:9
    at /Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/graceful-fs/graceful-fs.js:90:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:53:3)
 78% advanced chunk optimization/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/extract-text-webpack-plugin/dist/index.js:188
            chunk.sortModules();
                  ^

TypeError: chunk.sortModules is not a function
    at /Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/extract-text-webpack-plugin/dist/index.js:188:19
    at /Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/async/dist/async.js:3110:16
    at eachOfArrayLike (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/async/dist/async.js:1069:9)
    at eachOf (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/async/dist/async.js:1117:5)
    at Object.eachLimit (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/async/dist/async.js:3172:5)
    at Compilation.<anonymous> (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/extract-text-webpack-plugin/dist/index.js:184:27)
    at Compilation.applyPluginsAsyncSeries (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/webpack/node_modules/tapable/lib/Tapable.js:206:13)
    at Compilation.seal (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/webpack/lib/Compilation.js:579:8)
    at /Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/webpack/lib/Compiler.js:493:16
    at /Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/webpack/node_modules/tapable/lib/Tapable.js:289:11
    at _addModuleChain (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/webpack/lib/Compilation.js:481:11)
    at processModuleDependencies.err (/Users/rafaelcosta/workspace/React-Ninja/markdown-editor/node_modules/webpack/lib/Compilation.js:452:13)
    at process._tickCallback (internal/process/next_tick.js:61:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
@fdaciuk

**Comment by fdaciuk** [comment]
Oi @rafaelsevla! Provavelmente tem relação com a versão das dependências que você está usando. Você chegou a comparar com o [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md)?

Se sim, sobe seu projeto aqui no GitHub e passa o link que eu baixo aqui, testo, e vejo onde pode estar o problema :)

**Comment by rafaelsevla** [comment]
sim sim, ta igual essas dependências, fui checando sempre enquanto fazia as aulas

o projeto está nesse repo: https://github.com/rafaelsevla/markdown-editor

**Comment by fdaciuk** [comment]
Show! Vou baixar aqui e ver o que está acontecendo. Volto em breve com uma resposta :)

**Comment by fdaciuk** [comment]
Oi @rafaelsevla! Encontrei o problema: é na dependência `extract-text-webpack-plugin`.
Remova-o com:

```
yarn remove extract-text-webpack-plugin
```

E instale a v2:

```
yarn add --dev extract-text-webpack-plugin@2
```

Que vai funcionar :)

**Comment by rafaelsevla** [comment]
funcionou hehehe valeu @fdaciuk!!!

**Comment by fdaciuk** [comment]
Show! Já adicionei essa dependência no arquivo, para a aula 100 do módulo 2, que é onde fazemos o build dessa aplicação :)

Qualquer dúvida, avisa ae :)
