### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by gdalbelo** [da2k/curso-reactjs-ninja#367]
deu o seguinte problema ao executar: webpack-dev-server
```
$ webpack-dev-server
i ｢wds｣: Project is running at http://localhost:8080/                                                                     i ｢wds｣: webpack output is served from /dist/
i ｢wds｣: Content not from webpack is served from C:\Users\Vayon02\Projects\react-webpack
× ｢wdm｣: Hash: 4c14e28d05585c6881f1                                                                                       Version: webpack 4.39.2
                                                                 Time: 2065ms
        Built at: 2019-08-15 14:30:41
    Asset     Size  Chunks             Chunk Names                                                                        bundle.js  362 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./src/index 40 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]                                                               [./node_modules/html-entities/index.js] 231 bytes {main} [built]                                                          [./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]                                                        [./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
        [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]        [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.85 KiB {main} [built]
        [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./src/index.js] 1.48 KiB {main} [built] [failed] [1 error]                                                                   + 18 hidden modules

ERROR in ./src/index.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: Plugin/Preset files are not allowed to export objects, only functions. In C:\Users\Vayon02\Projects\react-webpack\node_modules\babel-preset-es2015\lib\index.js
    at createDescriptor (C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\config-descriptors.js:178:11)
    at items.map (C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\config-descriptors.js:109:50)
    at Array.map (<anonymous>)
    at createDescriptors (C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\config-descriptors.js:109:29)
    at createPresetDescriptors (C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\config-descriptors.js:101:10)
    at presets (C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\config-descriptors.js:47:19)
    at mergeChainOpts (C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\config-chain.js:320:26)
    at C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\config-chain.js:283:7
    at buildRootChain (C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\config-chain.js:120:22)
    at loadPrivatePartialConfig (C:\Users\Vayon02\Projects\react-webpack\node_modules\@babel\core\lib\config\partial.js:85:55)
i ｢wdm｣: Failed to compile.
```

Segue como estão os arquivos:
src/app.js
```js
'use strict'

var React = require('react')
var createReactClass = require('create-react-class');

var Title = createReactClass({
    render: function () {
        return React.createElement('h1', null, 'Título')
    }
})
```

src/index.js
```js
'use strict'

import Title from './app'

var React = require('react')
var ReactDOM = require('react-dom')

ReactDOM.render(
    React.createElement(Title),
    document.querySelector('[data-js="app"')
)

export default Title
```

package.json
```json
{
  "devDependencies": {
    "@babel/core": "^7.0.0-beta.40",
    "@babel/cli": "^7.0.0-beta.40",
    "babel-loader": "^8.0.6",
    "babel-plugin-lodash": "^3.3.2",
    "babel-plugin-react-transform": "^3.0.0",
    "@babel/preset-react": "^7.0.0-beta.40",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "webpack": "^4.20.2",
    "webpack-cli": "^3.1.1",
    "webpack-dev-server": "^3.8.0"
  },
  "dependencies": {
    "create-react-class": "^15.6.3",
    "react": "^16.9.0",
    "react-dom": "^16.9.0"
  }
}
```

Por favor me ajude a encontrar onde está o erro?

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @gdalbelo! Seu problema provavelmente é de configuração :)
Use as versões das dependências apresentadas [nesse arquivo](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) que deve funcionar corretamente :)

**Comment by gdalbelo** [comment]
resolvi o problema obrigado vou seguir com o curso o problema era que o babel não tinha sido instalado corretamente.

**Comment by fdaciuk** [comment]
Show @gdalbelo! Qualquer dúvida, só avisar :)
