### ISSUE TITLE
PROBLEMA, aula 16 (MRW#08 Configurando nossa aplicação para usar react hot loader);

### ISSUE THREAD

**Issue by JeanSaints** [da2k/curso-reactjs-ninja#382]
Olá professor, estou tendo problema ao rodar o `npm start`. Vou postar a msg de erro...

**
```

jean@jeanS:~/Dev-React-JS-Ninja/#02/react-webpack$ npm start

> @ start /home/jean/Dev-React-JS-Ninja/#02/react-webpack
> node server.js

/home/jean/Dev-React-JS-Ninja/#02/react-webpack/node_modules/webpack/lib/webpack.js:31
		throw new WebpackOptionsValidationError(webpackOptionsValidationErrors);
		^

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.module has an unknown property 'loaders'. These properties are valid:
   object { defaultRules?, exprContextCritical?, exprContextRecursive?, exprContextRegExp?, exprContextRequest?, noParse?, rules?, strictExportPresence?, strictThisContextOnImports?, unknownContextCritical?, unknownContextRecursive?, unknownContextRegExp?, unknownContextRequest?, unsafeCache?, wrappedContextCritical?, wrappedContextRecursive?, wrappedContextRegExp? }
   -> Options affecting the normal modules (`NormalModuleFactory`).
    at webpack (/home/jean/Dev-React-JS-Ninja/#02/react-webpack/node_modules/webpack/lib/webpack.js:31:9)
    at Object.<anonymous> (/home/jean/Dev-React-JS-Ninja/#02/react-webpack/server.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jean/.npm/_logs/2019-10-17T18_04_18_233Z-debug.log
jean@jeanS:~/Dev-React-JS-Ninja/#02/react-webpack$ 

```
**

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @JeanSaints! Você chegou a instalar a versão mostrada no [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md)? Usando as versões corretas, você não deve ter problemas :)

**Comment by JeanSaints** [comment]
Oi professor @fdaciuk acredito que instalei sim... mas vou rever e tentar novamente, ai depois lhe aviso... desde já obrigado!

**Comment by JeanSaints** [comment]
Professor @fdaciuk, o problema era o seguinte. Eu vinha instalando as dependências do Arquivo de Dependências, só que na instalação apareceu umas mensagens de vulnerabilidades, ai segui a sugestão de alteração. Agora refiz a instalação de todas dependências sem seguir a sugetão da vulnerabilidade e agora deu certo.

**Comment by fdaciuk** [comment]
Legal @JeanSaints! Pode ignorar essas mensagens de vulnerabilidades, pois as ferramentas que usamos são apenas para gerar os arquivos finais da aplicação, que são estáticos. As dependências nunca serão usadas em produção, então não precisa se preocupar com essas mensagens :)

Em breve também vou atualizar as aulas para refletir as versões mais recentes das ferramentas, isso já vai resolver também o problema com essas mensagens :)
