### ISSUE TITLE
learning-props erro ao executar

### ISSUE THREAD

**Issue by BrunoCursi** [da2k/curso-reactjs-ninja#403]
Bom dia,
estou tentando executar o exemplo learning-props
mas esta apresentando os erros abaixo

> @ start C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props
> node server.js

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'webpack-validator'
Require stack:
- C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props\webpack.config.js
- C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props\server.js        
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)     
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props\webpack.config.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\fontes\\curso-reactjs-ninja-master\\examples\\m01\\learning-props\\webpack.config.js',
PS C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props> npm start

> @ start C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props
> node server.js

internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'webpack-validator'
Require stack:
- C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props\webpack.config.js
- C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props\server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (C:\fontes\curso-reactjs-ninja-master\examples\m01\learning-props\webpack.config.js:5:18)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\fontes\\curso-reactjs-ninja-master\\examples\\m01\\learning-props\\webpack.config.js',
    'C:\\fontes\\curso-reactjs-ninja-master\\examples\\m01\\learning-props\\server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by fdaciuk** [comment]
Oi @BrunoCursi! Olhando a mensagem de erro:

```
Error: Cannot find module 'webpack-validator'
```

Está dizendo que ele não conseguiu encontrar o módulo `webpack-validator`. Você instalou esse módulo? :)

---

Obs.: sempre que abrir uma issue aqui, não apague o meu nome de usuário que já aparece na mensagem, senão eu não recebo notificação da sua dúvida, e posso acabar demorando a responder, ok? :)
