### ISSUE TITLE
MRW#06 - Meu webpack-dev-server quebrou!

### ISSUE THREAD

**Issue by moisesmedeiros7** [da2k/curso-reactjs-ninja#423]
No minuto 7 e 20 segundos eu não consegui mais acompanhar o curso porque meu webpack-dev-server quebrou:

moises@medeiros:~/Dropbox/Desenvolvimento/JavaScript/React/react-webpack$ webpack-dev-server 
 http://localhost:8080/webpack-dev-server/
webpack result is served from /static/
content is served from /home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack
Hash: 0080b668d2ff6b679dfb
Version: webpack 1.15.0
Time: 373ms

ERROR in ./src/index.js
Module build failed: Error: Couldn't find preset "stage=0" relative to directory "/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack"
    at /home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:293:19
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/home/moises/Dropbox/Desenvolvimento/JavaScript/React/react-webpack/node_modules/babel-loader/lib/index.js:46:20)
webpack: Failed to compile.

Pode me ajudar?

**Comment by moisesmedeiros7** [comment]
@fdaciuk meu arquivos:

**$ ls**
dist  index.html  node_modules  package.json  src  webpack.config.js


**.babelrc**
{
        "presets":[ "es2015", "stage=0"]
}
**webpack.config.js**
'use strict'
const path = require ('path')
module.exports = {
	entry: path.join(__dirname, 'src', 'index'),
	output: {
		path: path.join(__dirname,'dist'),
		filename: 'bundle.js',
		publicPath:'/dist/'
	},

module: {
	loaders: [{
		test: /\.js$/,
		exclude: /node_modules/,
		include: /src/,
		loader: 'babel'
	}]

}
	
}

**Comment by fdaciuk** [comment]
Oi @moisesmedeiros7! A dica de onde está o problema está na mensagem de erro:

```
ERROR in ./src/index.js
Module build failed: Error: Couldn't find preset "stage=0" relative to directory
```

Veja que você colocou `stage=0` (com um sinal de `=`) ao invés de `stage0` =)

**Comment by moisesmedeiros7** [comment]
Troquei por "stage-0" e **funcionou**. Só apareceu uma mensagem estranha no Console do Chrome:

:8080/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)"

Mas dá pra seguir adiante! Obrigado @fdaciuk

**Comment by fdaciuk** [comment]
isso aí! Essa mensagem do Chrome normalmente é sobre o favicon. O navegador vai tentar baixar automaticamente um favicon.ico à partir da raiz do seu projeto, se não tem nenhum definido no seu index.html. Quando ele não encontra esse arquivo, ele exibe esse erro.

Mas em desenvolvimento, pode ignorar sim :)
Para produção, é legal ter um favicon, mas nada que você precise se preocupar nesse momento :)
