### ISSUE TITLE
M2#A52 - Paginação - implementação inicial

### ISSUE THREAD

**Issue by pamplonapaulo** [da2k/curso-reactjs-ninja#430]
Olá, mestre. Eu de novo precisando de outro help. rsrs

Nessa aula, no que meu jest começa a testar o pagination/index.js, me deparo com esse erro:
```
 FAIL  src/utils/pagination/pagination.test.js
  ● Test suite failed to run

    Plugin/Preset files are not allowed to export objects, only functions. In /Applications/MAMP/htdocs/__FRONT/_react/_curso-daciuk/m2/working-with-assets/github-app/node_modules/babel-preset-es2015/lib/index.js

      at createDescriptor (node_modules/@babel/core/lib/config/config-descriptors.js:178:11)
      at items.map (node_modules/@babel/core/lib/config/config-descriptors.js:109:50)
          at Array.map (<anonymous>)
      at createDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:109:29)
      at createPresetDescriptors (node_modules/@babel/core/lib/config/config-descriptors.js:101:10)
      at presets (node_modules/@babel/core/lib/config/config-descriptors.js:47:19)
      at mergeChainOpts (node_modules/@babel/core/lib/config/config-chain.js:320:26)
      at node_modules/@babel/core/lib/config/config-chain.js:283:7
      at buildRootChain (node_modules/@babel/core/lib/config/config-chain.js:120:29)

----------|---------|----------|---------|---------|-------------------
File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
----------|---------|----------|---------|---------|-------------------
All files |       0 |        0 |       0 |       0 |                   
----------|---------|----------|---------|---------|-------------------
Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.295s
Ran all test suites related to changed files.

Watch Usage: Press w to show more.
```
Fiz umas buscas na web, gente aparentemente com o mesmo erro arrumou ao editar o .babelrc.

Mas o meu arquivo não está muito diferente do que os tutoriais mandam incluir. Eis o meu .babelrc:

```
{
    "presets": ["es2015", "stage-0", "react"],
    "plugins": ["react-hot-loader/babel"]
}
```

Pra poder avaliar melhor, eu suponho que você queira ver também o meu package.json:
```
{
  "scripts": {
    "start": "webpack-dashboard -- node server.js",
    "test": "jest --coverage",
    "test:watch": "yarn test -- --watch",
    "lint": "standard --verbose 'src/**/*.js'",
    "lint:watch": "gulp",
    "lint:fix": "standard --fix",
    "build": "cross-env NODE_ENV=production webpack --progress --config webpack.prod.config -p",
    "storybook": "start-storybook -p 6006 -c storybook",
    "build-storybook": "build-storybook -c storybook"
  },
  "devDependencies": {
    "@kadira/storybook": "^2.21.0",
    "babel-core": "^6.26.3",
    "babel-jest": "^25.1.0",
    "babel-loader": "^6.4.1",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "chai": "^4.2.0",
    "cross-env": "^7.0.2",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "^1.0.1",
    "gulp": "^3.9.1",
    "html-webpack-plugin": "^3.2.0",
    "jest-cli": "^25.1.0",
    "react-hot-loader": "^3.0.0-beta.2",
    "snazzy": "^8.0.0",
    "standard": "^14.3.1",
    "standard-loader": "^4.0.0",
    "style-loader": "^0.13.1",
    "webpack": "^1.15.0",
    "webpack-dashboard": "^3.2.0",
    "webpack-dev-server": "^1.16.5",
    "webpack-validator": "^3.0.1"
  },
  "dependencies": {
    "@fdaciuk/ajax": "^3.0.4",
    "react": "^15.4.2",
    "react-dom": "^15.4.2"
  },
  "standard": {
    "globals": [ "test", "it", "describe" ]
  }
}
```
Atualizei também meu repo:
https://github.com/pamplonapaulo/cursoReactjsNinjaBackup/tree/master/m2/working-with-assets/github-app

Me dá aquele help maroto de novo? rsrs

Abração e obrigado!

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @pamplonapaulo! O problema é só a versão do Jest e babel-jest :)
Seguindo as versões dessas duas dependências [passadas aqui](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md#m2a04), tudo vai rodar como esperado :)

**Comment by pamplonapaulo** [comment]
Mestre @fdaciuk, rodei estas versões novamente (já havia rodado quando assisti a aula M2#A04). O erro agora é o seguinte:

```
Determining test suites to run...2020-03-14 09:39 node[86904] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2020-03-14 09:39 node[86904] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event at:
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
paulopamplona@PAULOs-MacBook-Pro /Applications/MAMP/htdocs/__FRONT/_react/_curso-daciuk/m2/working-with-assets/github-app (dev) $ 

```

Alguma pista?

**Comment by fdaciuk** [comment]
Tenta remover a `node_modules` e o `yarn.lock` (ou `package-json.lock`), e instalar de novo (com `yarn` ou `npm install`) e veja se isso resolve. Deveria, mas se não rolar, avisa aqui que a gente vai testando outras coisas :)

**Comment by pamplonapaulo** [comment]
@fdaciuk Ok. Removi todos estes arquivos que você citou e rodei o yarn install. Mas infelizmente o erro persiste:

```
Determining test suites to run...2020-03-14 10:47 node[88160] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2020-03-14 10:47 node[88160] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2020-03-14 10:47 node[88160] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event at:
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
paulopamplona@PAULOs-MacBook-Pro /Applications/MAMP/htdocs/__FRONT/_react/_curso-daciuk/m2/working-with-assets/github-app (dev) $ 
```

**Comment by fdaciuk** [comment]
Estranho.. vc está rodando o comando `yarn test` quando recebe esse erro?

**Comment by pamplonapaulo** [comment]
@fdaciuk 'yarn test:watch'.

Limpei o cache de NPM e YARN e instalei tudo de novo via NPM. Nada muda. Mesmo erro.

**Comment by pamplonapaulo** [comment]
@fdaciuk to achando que vou trocar meu package.json pelo seu (https://github.com/da2k/curso-reactjs-ninja/blob/master/examples/m02/applications/github-app/package.json).

O seu está ligeiramente diferente. Que tu achas?

**Comment by pamplonapaulo** [comment]
mano @fdaciuk baixei praticamente todo o teu workflow (https://github.com/da2k/curso-reactjs-ninja/tree/master/examples/m02/applications/github-app). Só mantive meu src folder original.

Erro persistiu! Idêntico!

Daí resolvi arriscar. Acendi uma vela para Oxalá, apesar de ser 99% ateu, para tentar algo que essa turma aqui falou em 2018(https://stackoverflow.com/questions/51168732/fsevents-framework-fseventstreamstart-register-with-server-error-f2d-regist):

```
brew install watchman
```

Notei que no fim esse comando adicionou Python na minha máquina. E me lembrei que volta e meia tu sobe um servidor estático via Python no teu Terminal, nas aulas. Me pergunto se alguma coisa no pacote desse Jest ou Babel pede algo em Python.

Tipo, não faço a menor ideia de porque estava dando erro ou de porquê agora não dá. Mas foi com o comando acima que as coisas se resolveram. rs

**Comment by fdaciuk** [comment]
Opa! Conseguiu resolver então? Que trampo hein? :)
Não sei te dizer se tem alguma coisa a ver com o python em si, mas eu cheguei a acompanhar algumas notícias de problemas com essa lib `watchman`.

Não sei te dizer ao certo o que aconteceu, e se foi decidido algo com relação a remover alguma dependência. Talvez seja algo específico do sistema operacional (mac).

Enfim, que bom que conseguiu resolver :)
