### ISSUE TITLE
M2#A32 - Erro ao instalar html-webpack-plugin

### ISSUE THREAD

**Issue by jefferson-cruz** [da2k/curso-reactjs-ninja#458]
Após instalar a dependência, ao executar o npm start ocorre o erro abaixo:

> 
C:\Users\jefferson.cruz\Desktop\Cursos\React\CursoReactNinja\M02\working-with-assets\github-app\node_modules\html-webpack-plugin\lib\cached-child-compiler.js:182
    compiler.hooks.make.tapAsync(
                   ^

TypeError: Cannot read property 'make' of undefined
    at PersistentChildCompilerSingletonPlugin.apply (C:\Users\jefferson.cruz\Desktop\Cursos\React\CursoReactNinja\M02\working-with-assets\github-app\node_modules\html-webpack-plugin\lib\cached-child-compiler.js:182:20)
    at new CachedChildCompilation (C:\Users\jefferson.cruz\Desktop\Cursos\React\CursoReactNinja\M02\working-with-assets\github-app\node_modules\html-webpack-plugin\lib\cached-child-compiler.js:68:44)
    at HtmlWebpackPlugin.apply (C:\Users\jefferson.cruz\Desktop\Cursos\React\CursoReactNinja\M02\working-with-assets\github-app\node_modules\html-webpack-plugin\index.js:92:33)
    at Compiler.apply (C:\Users\jefferson.cruz\Desktop\Cursos\React\CursoReactNinja\M02\working-with-assets\github-app\node_modules\tapable\lib\Tapable.js:164:16)
    at WebpackOptionsApply.process (C:\Users\jefferson.cruz\Desktop\Cursos\React\CursoReactNinja\M02\working-with-assets\github-app\node_modules\webpack\lib\WebpackOptionsApply.js:62:18)
    at webpack (C:\Users\jefferson.cruz\Desktop\Cursos\React\CursoReactNinja\M02\working-with-assets\github-app\node_modules\webpack\lib\webpack.js:22:48)
    at Object.<anonymous> (C:\Users\jefferson.cruz\Desktop\Cursos\React\CursoReactNinja\M02\working-with-assets\github-app\server.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Abaixo segue o meu package.json e webpack.config
```
{
    "scripts": {
        "start": "node server.js"
    },
    "devDependencies": {
        "babel-core": "^6.26.3",
        "babel-loader": "^6.4.1",
        "babel-preset-es2015": "^6.24.1",
        "babel-preset-react": "^6.24.1",
        "babel-preset-stage-0": "^6.24.1",
        "html-webpack-plugin": "^4.2.1",
        "raw-loader": "^0.5.1",
        "react-hot-loader": "^3.0.0-beta.2",
        "standard": "^14.3.3",
        "standard-loader": "^4.0.0",
        "style-loader": "^0.13.1",
        "webpack": "^1.13.1",
        "webpack-dev-server": "^1.16.5",
        "webpack-validator": "^3.0.1"
    },
    "dependencies": {
        "@fdaciuk/ajax": "^3.0.4",
        "react": "^15.4.2",
        "react-dom": "^15.4.2"
    }
}

```
```
'use strict'

const path = require('path')
const webpack = require('webpack')
const validate = require('webpack-validator')

const HtmlWebpackPlugin = require('html-webpack-plugin')

module.exports = validate({
    devtool: 'source-map',
    entry: [
        'react-hot-loader/patch',
        'webpack-dev-server/client?http://localhost:3000',
        'webpack/hot/only-dev-server',
        path.join(__dirname, 'src', 'index')
    ],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'bundles.js',
        publicPath: ''
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new HtmlWebpackPlugin({
            title: 'GitHub App',
            template: path.join(__dirname, 'src', 'html', 'template.html')
        })
    ],
    module: {
        loaders: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                include: /src/,
                loader: 'babel'
            },
            {
                test: /\.css$/,
                exclude: /node_modules/,
                include: /src/,
                loaders: ['style', 'raw']
            }
        ]
    }
})
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @jefferson-cruz! Consegue subir o projeto em um repositório aqui no GitHub e compartilhar o link? Assim fica mais fácil de eu colocar pra rodar aqui o seu projeto, e tentar simular o mesmo problema :)

**Comment by deadlock** [comment]
Mesmo problema por aqui. Creio que seja alguma incompatibilidade de versões.

**Comment by deadlock** [comment]
Era isso mesmo. Tinha instalado a versão 4 (mais recente) do html plugin e mudei pra versão 1 pra testar. Com isso passou a subir normalmente o ambiente.

**Comment by fdaciuk** [comment]
Pois é.. a versão mais recente vai funcionar com a versão mais recente do webpack, porque as dependências evoluem de acordo com a lib principal :)
