### ISSUE TITLE
MRW#07

### ISSUE THREAD

**Issue by Lazaro1** [da2k/curso-reactjs-ninja#513]
Comecei o curso recentemente do React Ninja, estou na aula de configuração do Hot loader (MRW#07) , fiz a criação dos arquivos e instalação das dependências conforme dito na aula mas quando executo o npm start aparece essa mensagem.
```
$ npm start

> @ start C:\projetos\react_ninja
> node server.js

C:\projetos\react_ninja\node_modules\webpack-dev-server\lib\utils\updateCompiler.js:51
      compiler.hooks.entryOption.call(config.context, config.entry);
                     ^

TypeError: Cannot read property 'entryOption' of undefined
    at C:\projetos\react_ninja\node_modules\webpack-dev-server\lib\utils\updateCompiler.js:51:22
    at Array.forEach (<anonymous>)
    at updateCompiler (C:\projetos\react_ninja\node_modules\webpack-dev-server\lib\utils\updateCompiler.js:49:15)
    at new Server (C:\projetos\react_ninja\node_modules\webpack-dev-server\lib\Server.js:72:5)
    at Object.<anonymous> (C:\projetos\react_ninja\server.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lazaro\AppData\Roaming\npm-cache\_logs\2020-10-09T02_01_11_848Z-debug.log

```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @Lazaro1! Consegue subir seu projeto aqui no GitHub e postar o link do repositório aqui pra eu dar uma olhada? :)

**Comment by Lazaro1** [comment]
https://github.com/Lazaro1/react_ninja

**Comment by fdaciuk** [comment]
Pronto! O problema é que você está usando o [webpack-dev-server na v3](https://github.com/Lazaro1/react_ninja/blob/master/package.json#L13), não na v1, como mostrado no [arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) :)

**Comment by Lazaro1** [comment]
Deu certo, Obrigado !

**Comment by fdaciuk** [comment]
Show! Qualquer dúvida, só avisar :)
