### ISSUE TITLE
MWR#02

### ISSUE THREAD

**Issue by KasluCaetano** [da2k/curso-reactjs-ninja#535]
```
PS C:\Users\Lucas Caetano\Desktop\CURSO REACT NINJAS\master\src> webpack
CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm WARN webpack-cli@4.5.0 requires a peer of webpack@4.x.x || 5.x.x but none is installed. You must install peer dependencies yourself.
npm WARN @webpack-cli/configtest@1.0.1 requires a peer of webpack@4.x.x || 5.x.x but none is installed. You must install peer dependencies yourself.
npm WARN master No description
npm WARN master No repository field.
npm WARN master No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ webpack-cli@4.5.0
updated 1 package and audited 400 packages in 3.816s

3 packages are looking for funding
  run `npm fund` for details

found 6 vulnerabilities (4 low, 1 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Error: Cannot find module 'webpack-cli/package.json'
Require stack:
- C:\Users\Lucas Caetano\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at runCli (C:\Users\Lucas Caetano\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:50:26)
    at C:\Users\Lucas Caetano\AppData\Roaming\npm\node_modules\webpack\bin\webpack.js:139:5
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\Users\\Lucas Caetano\\AppData\\Roaming\\npm\\node_modules\\webpack\\bin\\webpack.js'
  ]
```

Boa tarde Professor, eu não esotu conseguindo executar o webpack, da esse erro mesmo exutando o comando: npm i -g webpack.

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @KasluCaetano! Você está com uma versão do webpack diferente da que foi usada no curso :)
O que você precisa fazer para resolver é desinstalar a versão que está usando e instalar versão correta, que está listada no nosso
[arquivo de dependências](https://github.com/da2k/curso-reactjs-ninja/blob/master/versions-of-dependencies.md) :)

Se tiver qualquer problema, comenta aqui que eu te ajudo, ok? :)

**Comment by fdaciuk** [comment]
Oi @KasluCaetano! Conseguiu resolver? Vou fechar a issue, mas se você ainda tiver problemas, só avisar :)
