### ISSUE TITLE
M2#A51 - problemas com o gulp

### ISSUE THREAD

**Issue by CheeseFlan** [da2k/curso-reactjs-ninja#56]
Professor estou tendo esse erro ao executar o gulp;
```
[11:36:08] Using gulpfile c:\dev\react_course\react-webpack-with-assets\gulpfile.js
[11:36:08] Starting 'lint'...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn yarn ENOENT
    at exports._errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:192:19)
    at onErrorNT (internal/child_process.js:374:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-webpack@1.0.0 lint:watch: `gulp`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-webpack@1.0.0 lint:watch script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Johnn\AppData\Roaming\npm-cache\_logs\2017-09-27T14_36_08_977Z-debug.log
```
oque poderia ser, já testei colocando no lugar do `yarn` o `npm run` ou só o `npm`, e não funcionou :(

@fdaciuk

**Comment by fdaciuk** [comment]
Fala @CheeseFlan :D 
Esse é um problema específico do windows. Para resolver, instale essa dependência:
https://github.com/fdaciuk/workflow-reactjs/blob/master/gulpfile.js#L6-L7

**Comment by CheeseFlan** [comment]
Vlw professor, funcionou :+1:

**Comment by fdaciuk** [comment]
Show \o/
