### ISSUE TITLE
Não consigo gerar o bundle.js utilizando o comando webpack no terminal

### ISSUE THREAD

**Issue by marceloturler** [da2k/curso-reactjs-ninja#592]
-- Meu webpack.config.js está assim:
```
'use strict'

const path = require('path')

module.exports = {
  entry: path.join(__dirname, 'src', 'index'),
  output: {
    path: path.join(__dirname, 'dist'),
    filename: 'bundle.js',
    publicPath: '/static/'
  }
}
```
![ERRO_GERACAO_BUNDLE](https://user-images.githubusercontent.com/54109962/189998344-f72317fc-d49c-4339-ace5-44661b846673.png)

-- Meu package.json está assim:
```
{
  "scripts": {
    "web": "webpack",
    "dev": "webpack-dev-server"
  },
  "devDependencies": {
    "webpack": "^1.13.1",
    "webpack-dev-server": "^1.16.5"
  },
  "dependencies": {
    "nodejs": "0.0.0"
  }
}
```

Estou com grande dificuldade de fazer seu curso, pois não consigo gerar o bundle.js e nem colocar pra rodar o webpack-dev-server ( mesmo ambos estando na versão correta do curso 1.13.1 e igualmente o nodejs 10.0..0 ), conforme suas recomendações. Procurei em diversos locais na Internet, mas não encontrei nenhuma solução viável. Vi as respostas dos demais alunos e testei algumas coisas por conta própria, mas nada até agora. Pode me ajudar, por favor?

Instalei local e global, conforme suas instruções. Sem nenhum sucesso. Sempre esta mensagem de erro.

-- O erro que aparece é este ( abaixo ):
```
G:\CURSOS\REACT-NINJA\react-webpack>webpack
Hash: 0080b668d2ff6b679dfb
Version: webpack 1.13.1
Time: 20ms
   [0] ./src/index.js 0 bytes [built] [failed]

ERROR in ./src/index.js
Module parse failed: G:\CURSOS\REACT-NINJA\react-webpack\src\index.js Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '�' (1:0)
    at Parser.pp$4.raise (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\acorn\dist\acorn.js:2221:15)
    at Parser.pp$7.getTokenFromCode (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\acorn\dist\acorn.js:2756:10)
    at Parser.pp$7.readToken (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\acorn\dist\acorn.js:2477:17)
    at Parser.pp$7.nextToken (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\acorn\dist\acorn.js:2468:15)
    at Parser.parse (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\acorn\dist\acorn.js:515:10)
    at Object.parse (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\acorn\dist\acorn.js:3098:39)
    at Parser.parse (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\webpack\lib\Parser.js:902:15)
    at NormalModule.<anonymous> (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\webpack\lib\NormalModule.js:104:16)
    at NormalModule.onModuleBuild (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:310:10)
    at nextLoader (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:275:25)
    at G:\CURSOS\REACT-NINJA\react-webpack\node_modules\webpack-core\lib\NormalModuleMixin.js:259:5
    at Storage.finished (G:\CURSOS\REACT-NINJA\react-webpack\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:38:16)
    at G:\CURSOS\REACT-NINJA\react-webpack\node_modules\graceful-fs\graceful-fs.js:123:16     
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:408:3)
```

@fdaciuk

**Comment by fdaciuk** [comment]
Oi @marceloturler! Pode abrir a pergunta em um lugar só, eu olho todos os lugares, ok? =)

Te respondi lá pela Udemy, então vamos manter a conversa por lá, para centralizar as respostas, pode ser?

Abraços!

**Comment by marceloturler** [comment]
Fala Fernando, combinado!

Eu enviei pelo github por causa de um conselho seu na página do curso. Daí, pra agilizar postei neste tb.
Mas nos falamos por lá.

Grato pela ajuda!
________________________________
De: Fernando Daciuk ***@***.***>
Enviado: terça-feira, 13 de setembro de 2022 23:38
Para: da2k/curso-reactjs-ninja ***@***.***>
Cc: MARCELO ELIAS TURLER ***@***.***>; Mention ***@***.***>
Assunto: Re: [da2k/curso-reactjs-ninja] Não consigo gerar o bundle.js utilizando o comando webpack no terminal (Issue #592)


Oi @marceloturler<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmarceloturler&data=05%7C01%7C%7C8c2b50ab54f14ba9c05908da95e1215d%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637987091427597828%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=szoNVyQhe9SaEwf6gteUhtVHbLFopPbWrpNqJy3Pmx8%3D&reserved=0>! Pode abrir a pergunta em um lugar só, eu olho todos os lugares, ok? =)

Te respondi lá pela Udemy, então vamos manter a conversa por lá, para centralizar as respostas, pode ser?

Abraços!
